on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs : 
  build-node:
    runs-on: ubuntu-latest
    container: node:19
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
        working-directory: ./node-express
#       - run: npm run server-dev
#         working-directory: ./node-express
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./node-express
          recurse: true
          output_dir: ./out
