on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs : 
  build-node:
    runs-on: ubuntu-latest
    container: node:19
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run server
